project:
  type: book
  execute-dir: project
  output-dir: docs

book:
  title: "Gaming Reduction Experiment"
  author: "Digital Wellbeing Lab"
  date: "2025-06-06"
  chapters:
    - index.qmd
    - scripts/sim_self_report.qmd
    - scripts/sim_sleepquality_report.qmd
    - scripts/sim_comp_report.qmd
  search: true
  repo-url: https://digital-wellbeing.github.io/gaming-reduction-backend/
  downloads: [pdf]

comments:
  hypothesis: true

toc: true
editor_options:
  chunk_output_type: console
execute:
  warning: false
  message: false
  output: true
  echo: true
  cache: true
knitr:
  opts_chunk:
    root.dir: .
page-layout: full
format:
  html:
    theme:
      light: united
      dark: darkly
    code-fold: true
    fontsize: 13pt
    other-links:
      - text: Participant FAQs
        href: https://digital-wellbeing.github.io/oxford-gaming-study/
        icon: link
      - text: GitHub Repository
        href: https://github.com/digital-wellbeing/gaming-reduction-backend
        icon: github
# bibliography: references.bib
publish:
  gh-pages:
    branch: main
    folder: docs
